## 08 - Async Await Error Handling

### Topics Covered

- Two examples for handling errors
  - One with the try...catch block inside the same async function
  - The other with the .catch() we've used before
